#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tcp-communications-pkg==0.0.0','console_scripts','server_node'
__requires__ = 'tcp-communications-pkg==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tcp-communications-pkg==0.0.0', 'console_scripts', 'server_node')()
    )
